variables:
  CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
  CONAN_PASSWORD: $(CONAN_PASSWORD)

resources:
  repositories:
    - repository: templates
      type: github
      name: Croydon/templates
      endpoint: github

jobs:
- template: .ci/azure.yml@templates
  parameters:
    splitByBuildTypes: "true"
